// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiToken": string;
      "modelVersion": string;
      "language": string;
      "isOcr": boolean;
      "enableFormula": boolean;
      "enableTable": boolean;
      "autoConvert": boolean;
      "exportDir": string;
      "exportPerItem": boolean;
      "exportLastType": string;
      "useLocalApi": boolean;
      "localApiUrl": string;
      "localApiType": string;
      "localRouterConcurrency": number;
    };
  }
}
